// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mudoqsespdusvxblahvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11ZG9xc2VzcGR1c3Z4YmxhaHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDU1NjYsImV4cCI6MjA2NDAyMTU2Nn0.71xuwSYZewjelIilnHWwfyBHEu350Jv67Cc9j3Ap1Cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});